### ISSUE TITLE
Error parsing result SyntaxError: Unexpected token H in JSON at position 0

### ISSUE THREAD

**Issue by mishushakov** [rocket-connect/graphql-debugger#66]
```ts
import {
  GraphQLOTELContext,
  traceSchema,
} from "@graphql-debugger/trace-schema";

import { g, InferResolvers, buildSchema } from 'garph'
import { createYoga, YogaInitialContext } from 'graphql-yoga'
import { createServer } from 'http'

const queryType = g.type('Query', {
  greet: g.string()
    .args({
      name: g.string().optional().default('Max')
    })
    .description('Greets a person')
})

const resolvers: InferResolvers<{ Query: typeof queryType }, { context: YogaInitialContext }> = {
  Query: {
    greet: (parent, args, context, info) => `Hello, ${args.name}`
  }
}

const schema = buildSchema({ g, resolvers })

// Wrap all resolvers and fields with tracing
const tracedSchema = traceSchema({
  schema,
});

const yoga = createYoga({
  schema: tracedSchema,
  context: (req) => {
    return {
      // Include variables, result and context in traces
      GraphQLOTELContext: new GraphQLOTELContext({
        includeVariables: true,
        includeResult: true,
        includeContext: true,
      }),
    };
  },
});

const server = createServer(yoga)
server.listen(4000, () => {
  console.info('Server is running on http://localhost:4000/graphql')
})
```

Output:

```
  @graphql-debugger:cli Starting debugger +0ms
  @graphql-debugger:backend Starting application +0ms
  @graphql-debugger:queue Queue Starting +0ms
  @graphql-debugger:queue Queue Started +1ms
  @graphql-debugger:queue Queue Starting +0ms
  @graphql-debugger:queue Queue Started +0ms
  @graphql-debugger:backend Starting app +141ms
  @graphql-debugger:backend GraphQL online on port:  16686 +1ms
  @graphql-debugger:backend Collector online on port:  4318 +0ms
  @graphql-debugger:backend Application started +0ms
  @graphql-debugger:cli Debugger Online http://localhost:16686 +143ms
  @graphql-debugger:collector-proxy Request POST /v1/schema +0ms
  @graphql-debugger:collector-proxy POST /v1/schema +1ms
  @graphql-debugger:queue Queue Adding +4m
  @graphql-debugger:collector-proxy Worker started +9ms
  @graphql-debugger:collector-proxy Worker finished +9ms
  @graphql-debugger:queue Queue Added +10ms
  @graphql-debugger:collector-proxy Request POST /v1/traces +1m
  @graphql-debugger:collector-proxy POST /v1/traces +6ms
  @graphql-debugger:queue Queue Adding +1m
  @graphql-debugger:collector-proxy Worker started +1ms
  @graphql-debugger:collector-proxy Error parsing result SyntaxError: Unexpected token H in JSON at position 0
    at JSON.parse (<anonymous>)
    at /Users/mish/Documents/Playground/graphql-debugger/node_modules/@graphql-debugger/collector-proxy/build/workers/post-traces.js:109:38
    at Array.map (<anonymous>)
    at postTracesWorker (/Users/mish/Documents/Playground/graphql-debugger/node_modules/@graphql-debugger/collector-proxy/build/workers/post-traces.js:73:44) +4ms
  @graphql-debugger:collector-proxy Error creating spans SyntaxError: Unexpected token H in JSON at position 0
    at JSON.parse (<anonymous>)
    at /Users/mish/Documents/Playground/graphql-debugger/node_modules/@graphql-debugger/collector-proxy/build/workers/post-traces.js:109:38
    at Array.map (<anonymous>)
    at postTracesWorker (/Users/mish/Documents/Playground/graphql-debugger/node_modules/@graphql-debugger/collector-proxy/build/workers/post-traces.js:73:44) +1ms
  @graphql-debugger:collector-proxy Worker finished +0ms
```

**Comment by mishushakov** [comment]
Same here:

```ts
import {
  GraphQLOTELContext,
  traceSchema,
} from "@graphql-debugger/trace-schema";

import { makeExecutableSchema } from "@graphql-tools/schema";
import { createYoga, YogaInitialContext } from 'graphql-yoga'
import { createServer } from 'http'

const schema = makeExecutableSchema({
  typeDefs: `
    type Query {
      hello: String!
    }
  `,
  resolvers: {
    Query: {
      hello: () => "world",
    },
  },
})

// Wrap all resolvers and fields with tracing
const tracedSchema = traceSchema({
  schema
});

const yoga = createYoga({
  schema: tracedSchema,
  context: (req) => {
    return {
      // Include variables, result and context in traces
      GraphQLOTELContext: new GraphQLOTELContext({
        includeVariables: true,
        includeResult: true,
        includeContext: true,
      }),
    };
  },
});

const server = createServer(yoga)
server.listen(4000, () => {
  console.info('Server is running on http://localhost:4000/graphql')
})
```

**Comment by danstarns** [comment]
Hey @mishushakov thank you for reporting, I was able to reproduce and I made a fix here https://github.com/rocket-connect/graphql-debugger/commit/fd70a2266871d8a3d342e137e3b84b133421521f

If you download the latest as of writing `0.0.0-alpha.51` this should now work.
