### ISSUE TITLE
TypeError: parentTracer.getSpanLimits is not a function

### ISSUE THREAD

**Issue by danstarns** [rocket-connect/graphql-debugger#72]
```
ERR TypeError: parentTracer.getSpanLimits is not a function
    at new Span (/Users/danielstarns/code/test/node_modules/@opentelemetry/sdk-trace-base/src/Span.ts:121:37)
    at runInSpan (/Users/danielstarns/code/test/node_modules/@graphql-debugger/opentelemetry/build/run-in-span.js:11:22)
    at resolve (/Users/danielstarns/code/test/node_modules/@graphql-debugger/trace-directive/build/trace-directive.js:55:80)
    at executeField (/Users/danielstarns/code/test/node_modules/@graphql-tools/executor/cjs/execution/execute.js:331:24)
    at executeFields (/Users/danielstarns/code/test/node_modules/@graphql-tools/executor/cjs/execution/execute.js:271:28)
    at collectAndExecuteSubfields (/Users/danielstarns/code/test/node_modules/@graphql-tools/executor/cjs/execution/execute.j
```

**Comment by danstarns** [comment]
Fixed in: https://github.com/rocket-connect/graphql-debugger/commit/6030f9baea0aaa6b71b4f6a3fec8513d4c87254e
